### ISSUE TITLE
Trouble using in Blender 3.1 / Blender 3.2

### ISSUE THREAD

**Issue by fire** [eliemichel/DagAmendment#2]
Version: https://github.com/eliemichel/DagAmendment/releases/tag/v1.0.1

System: Windows 11, RTX 3000 series Nvidia

I can't seem to compile DagAmendment for Blender 3.1/3.2.

Reproduction steps:

1. git clone https://github.com/eliemichel/DagAmendment
2. cd Accel
3. cmake .. -DPYTHON_EXECUTABLE="C:\Users\USER\scoop\apps\python\current\python.EXE" -GNinja
4. ninja
5. ninja install

Notes:

Seems to be using python 3.10. Your previous releases use python 3.9.

**Comment by eliemichel** [comment]
Does `C:\Users\USER\scoop\apps\python\current\python.EXE" --version` says it is Python 3.10? If not, you should install Python 3.10

**Comment by fire** [comment]
```
>C:\Users\USER\scoop\apps\python\current\python.EXE --version
Python 3.10.4
```

**Comment by eliemichel** [comment]
Could you give more details about what goes wrong, e.g., compiling error?
I just uploaded a few fixes, make sure to pull. Also [v1.1.0](https://github.com/eliemichel/DagAmendment/releases/tag/v1.1.0) should be compatible with Blender 3.10!

**Comment by fire** [comment]
Thanks I tested your build and it worked.
