### ISSUE TITLE
Extract as an OpenMfx node

### ISSUE THREAD

**Issue by fire** [eliemichel/DagAmendment#3]
How much effort would be to extract this as a OpenMFX node and can you sketch a technical design for it?

**Comment by eliemichel** [comment]
It does not really make sense to extract the DAG Amendment as a node, or maybe I misunderstood what you meant.

What is possible though is to use the OpenMfx modifier from [the OpenMfx branch](https://github.com/eliemichel/OpenMfxForBlender) to build your parametric asset and then use the DAG amendment for it. You will need to inform the DAG Amendment add-on of how to handle your custom modifiers by **(i)** returning in [`get_node_duplication_count`](https://github.com/eliemichel/DagAmendment/blob/main/DagAmendment/dag_amendment_operators.py#L90) the number of duplicates it may create and **(ii)** in [`insert_nodes_rec`](https://github.com/eliemichel/DagAmendment/blob/main/DagAmendment/dag_amendment_operators.py#L139) insert nodes before/after.

**Comment by fire** [comment]
I'll pose a question.

Let's say I want to create a parametric chair / human as a OpenMFX modifier on a position and the input hyper parameters.

I'm not sure how to expose this to let's say Godot Engine which could be a OpenMFX host.

The DAG Amendment applies modifications on a mesh via strokes to optimize hyperparameters based on the uv'd surface. Not sure how that integrates.

**Comment by eliemichel** [comment]
I don't get what exactly bothers you tbh

**Comment by fire** [comment]
Ah nevermind.
