### ISSUE TITLE
Blender 3.3 does not load dag amendment

### ISSUE THREAD

**Issue by fire** [eliemichel/DagAmendment#4]
### Issue description

Blender 3.3 does not load dag amendment

### Steps to reproduce

1. Download dag admendment
2. Install into blender 3.3 addons
3. Can't dag amend

### Using a released version?

Yes. https://github.com/eliemichel/DagAmendment/releases/tag/v1.1.0

### What OS? Any other relevant information?

Windows 11, Nvidia

**Comment by eliemichel** [comment]
Hi @fire thanks for your feedback.

Are you able to reach this state?

![image](https://user-images.githubusercontent.com/5802849/200128324-3f921a70-b97d-4993-9794-f8c9b824cc8c.png)

Whether or not, could you report what is logged in the system console? (Window > Toggle System Console).

**Comment by fire** [comment]
Downloaded https://github.com/eliemichel/DagAmendment/releases/download/v1.1.0/DagAmendment-v1.1.0.zip.

Installed via zip.

I can't reproduce.

On a fresh windows 11 install.. and I have scoop.

```
powershell
> python --version
Python 3.10.6
```

```
BLENDER
PYTHON INTERACTIVE CONSOLE 3.10.2
```

I think what happened was scoop install python upgraded to python 3.11.

Can close if you wish.

**Comment by eliemichel** [comment]
Okey, the version of the system-wide Python should not affect Blender since it comes with its own Python, but good to keep in mind.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/201117402-0ed0c043-7e2a-457b-b1fd-408d6e8f06e4.png)

**Comment by eliemichel** [comment]
Oh I forgot to update the linux binary, I just updated the zip of https://github.com/eliemichel/DagAmendment/releases/tag/v1.1.0 with the new linux build!
